#!/usr/bin/env bash

usage() {
cat << EOM
$0: $0 [pict-author-name]
EOM
  exit 0
}

if [ $# -lt 1 ] ; then
  usage
fi

ARCHIVE_DIR="./$1"

if [ ! -d "$ARCHIVE_DIR" ] ; then
cat << EOM
Attension: mkdir OK? : "$ARCHIVE_DIR" 
EOM
  echo -n "> "
  read -r ANS
  mkdir "$ARCHIVE_DIR"
fi

MOVE_ZIP_PATTERN="${1}-*.zip"
ls $MOVE_ZIP_PATTERN > /dev/null 2>&1
if [ $? -eq 0 ] ; then 
	mv $MOVE_ZIP_PATTERN $ARCHIVE_DIR

	pushd $ARCHIVE_DIR

	unzip *.zip
	find . -type f -exec mv {} ./ \;
	find . -type d -exec rmdir {} \;
	popd
fi

MOVE_IMG_PATTERN="${1}-*img*"
ls $MOVE_IMG_PATTERN > /dev/null 2>&1
if [ $? -eq 0 ] ; then 
	mv ${MOVE_IMG_PATTERN} $ARCHIVE_DIR
	pushd $ARCHIVE_DIR

	find . -type f -exec mv {} ./ \;
	find . -type d -exec rmdir {} \;
	popd
fi


